arbitrumsepolia:
  interchainSecurityModule:
    modules:
      - relayer: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  isNft: false
  owner: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
  proxyAdmin:
    address: "0x6fB6AE831862Fa0A40720dFD58E1B66C7cdaf62b"
    owner: "0x8B4a01A9aac61f22717dF5efFfD30B7DD96A8F09"
  type: synthetic
liberichain:
  interchainSecurityModule:
    modules:
      - relayer: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  isNft: false
  owner: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
  proxyAdmin:
    address: "0xEDa49a212DF8150cD485fE9C127BcbFB6Ccc9006"
    owner: "0x48dbd38158560FF375Ef20AF7DF0C6c2176Fb790"
  token: "0xcC4b6914EA2d4dd6674D73e4827A31B3B5eef17A"
  type: collateral

